### ISSUE TITLE
нужна помощь)

### ISSUE THREAD

**Issue by SacredCurse666** [w1png/shop-telegram-bot#10]
![image](https://user-images.githubusercontent.com/72343832/231741329-e3475796-e0b6-451a-bdc0-1961254286d5.png)
как пофиксить?)

**Comment by Mersh-NI** [comment]
Установи требуемый модуль. 
pip install aioschebule

**Comment by w1png** [comment]
Бот пока что не поддерживается, особенно ветка rewrite
