### ISSUE TITLE
[ПРЕДЛОЖЕНИЕ] ID пользователя

### ISSUE THREAD

**Issue by nikitas244** [w1png/shop-telegram-bot#4]
Здравствуйте. Очень понравился Ваш бот и увидел что Вы его обновляете, но новую версию я не смог запустить, пока предложение по первой версии.

Возможно-ли сделать чтобы ID пользователя в заказах подсвечивался или подхватывался юзернейм?

**Comment by w1png** [comment]
Юзернейм в заказах будет, про "подсвечивался" не понял. 1.0.0 не будет больше обновляться из-за плохого кода, тк проект был написан как проект для учебного заведения.

**Comment by nikitas244** [comment]
Если юзернейма нет, то хотел чтобы поле "ID" покупателя подсвечивался чтобы можно было перейти по нему в профиль телеги, но если в будущем добавите отдельное поле юзернейма, то будет круто.

И вот ещё, опять же про первую версию, оповещений, о смене заказа на "готов", нет? Включил в настройках, меняю заказ на "готов", но пользователю никаких оповещений не поступает.

**Comment by nikitas244** [comment]
И с rewrite версией, её сейчас возможно запустить? 

Хотелось "поклацать" её, а не нашел ни как запустить под виндой её и смены токена бота.

**Comment by w1png** [comment]
> Если юзернейма нет, то хотел чтобы поле "ID" покупателя подсвечивался чтобы можно было перейти по нему в профиль телеги, но если в будущем добавите отдельное поле юзернейма, то будет круто.

Понял, будет сделано 

> И вот ещё, опять же про первую версию, оповещений, о смене заказа на "готов", нет? Включил в настройках, меняю заказ на "готов", но пользователю никаких оповещений не поступает. 

Это недоработка, в 2.0 будет сделано :)
Сегодня посмотрю получится ли сделать в 1.0

**Comment by w1png** [comment]
> И с rewrite версией, её сейчас возможно запустить? 
> 
> 
> 
> Хотелось "поклацать" её, а не нашел ни как запустить под виндой её и смены токена бота.

Там еще мало что готово, но если интересует попробовать, отпишите в тг: t.me/w1png

**Comment by w1png** [comment]
[Готово](https://github.com/w1png/shop-telegram-bot/releases/tag/v1.0.1)
